// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: pro/models/ring_density_model.proto

package ring_density_model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RingDensity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Code          string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description   string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	HasRotaryPlug bool   `protobuf:"varint,5,opt,name=hasRotaryPlug,proto3" json:"hasRotaryPlug,omitempty"`
}

func (x *RingDensity) Reset() {
	*x = RingDensity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_models_ring_density_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RingDensity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RingDensity) ProtoMessage() {}

func (x *RingDensity) ProtoReflect() protoreflect.Message {
	mi := &file_pro_models_ring_density_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RingDensity.ProtoReflect.Descriptor instead.
func (*RingDensity) Descriptor() ([]byte, []int) {
	return file_pro_models_ring_density_model_proto_rawDescGZIP(), []int{0}
}

func (x *RingDensity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RingDensity) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RingDensity) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RingDensity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RingDensity) GetHasRotaryPlug() bool {
	if x != nil {
		return x.HasRotaryPlug
	}
	return false
}

type Density struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Density []*RingDensity `protobuf:"bytes,1,rep,name=density,proto3" json:"density,omitempty"`
}

func (x *Density) Reset() {
	*x = Density{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_models_ring_density_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Density) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Density) ProtoMessage() {}

func (x *Density) ProtoReflect() protoreflect.Message {
	mi := &file_pro_models_ring_density_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Density.ProtoReflect.Descriptor instead.
func (*Density) Descriptor() ([]byte, []int) {
	return file_pro_models_ring_density_model_proto_rawDescGZIP(), []int{1}
}

func (x *Density) GetDensity() []*RingDensity {
	if x != nil {
		return x.Density
	}
	return nil
}

type RingDensityMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Density map[string]*Density `protobuf:"bytes,1,rep,name=density,proto3" json:"density,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *RingDensityMap) Reset() {
	*x = RingDensityMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_models_ring_density_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RingDensityMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RingDensityMap) ProtoMessage() {}

func (x *RingDensityMap) ProtoReflect() protoreflect.Message {
	mi := &file_pro_models_ring_density_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RingDensityMap.ProtoReflect.Descriptor instead.
func (*RingDensityMap) Descriptor() ([]byte, []int) {
	return file_pro_models_ring_density_model_proto_rawDescGZIP(), []int{2}
}

func (x *RingDensityMap) GetDensity() map[string]*Density {
	if x != nil {
		return x.Density
	}
	return nil
}

var File_pro_models_ring_density_model_proto protoreflect.FileDescriptor

var file_pro_models_ring_density_model_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x72, 0x69, 0x6e,
	0x67, 0x5f, 0x64, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x65, 0x6e, 0x73,
	0x69, 0x74, 0x79, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x8f, 0x01, 0x0a, 0x0b, 0x52, 0x69,
	0x6e, 0x67, 0x44, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x68, 0x61, 0x73, 0x52, 0x6f, 0x74, 0x61,
	0x72, 0x79, 0x50, 0x6c, 0x75, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x68, 0x61,
	0x73, 0x52, 0x6f, 0x74, 0x61, 0x72, 0x79, 0x50, 0x6c, 0x75, 0x67, 0x22, 0x44, 0x0a, 0x07, 0x44,
	0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x12, 0x39, 0x0a, 0x07, 0x64, 0x65, 0x6e, 0x73, 0x69, 0x74,
	0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x64,
	0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x69, 0x6e,
	0x67, 0x44, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x52, 0x07, 0x64, 0x65, 0x6e, 0x73, 0x69, 0x74,
	0x79, 0x22, 0xb4, 0x01, 0x0a, 0x0e, 0x52, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x6e, 0x73, 0x69, 0x74,
	0x79, 0x4d, 0x61, 0x70, 0x12, 0x49, 0x0a, 0x07, 0x64, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x65, 0x6e,
	0x73, 0x69, 0x74, 0x79, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x69, 0x6e, 0x67, 0x44,
	0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x4d, 0x61, 0x70, 0x2e, 0x44, 0x65, 0x6e, 0x73, 0x69, 0x74,
	0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x64, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x1a,
	0x57, 0x0a, 0x0c, 0x44, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x31, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x44, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6c, 0x65, 0x78, 0x61, 0x6e, 0x64, 0x65, 0x72,
	0x32, 0x37, 0x32, 0x2f, 0x73, 0x65, 0x61, 0x6c, 0x75, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f,
	0x72, 0x69, 0x6e, 0x67, 0x5f, 0x64, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pro_models_ring_density_model_proto_rawDescOnce sync.Once
	file_pro_models_ring_density_model_proto_rawDescData = file_pro_models_ring_density_model_proto_rawDesc
)

func file_pro_models_ring_density_model_proto_rawDescGZIP() []byte {
	file_pro_models_ring_density_model_proto_rawDescOnce.Do(func() {
		file_pro_models_ring_density_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_pro_models_ring_density_model_proto_rawDescData)
	})
	return file_pro_models_ring_density_model_proto_rawDescData
}

var file_pro_models_ring_density_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pro_models_ring_density_model_proto_goTypes = []interface{}{
	(*RingDensity)(nil),    // 0: ring_density_model.RingDensity
	(*Density)(nil),        // 1: ring_density_model.Density
	(*RingDensityMap)(nil), // 2: ring_density_model.RingDensityMap
	nil,                    // 3: ring_density_model.RingDensityMap.DensityEntry
}
var file_pro_models_ring_density_model_proto_depIdxs = []int32{
	0, // 0: ring_density_model.Density.density:type_name -> ring_density_model.RingDensity
	3, // 1: ring_density_model.RingDensityMap.density:type_name -> ring_density_model.RingDensityMap.DensityEntry
	1, // 2: ring_density_model.RingDensityMap.DensityEntry.value:type_name -> ring_density_model.Density
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pro_models_ring_density_model_proto_init() }
func file_pro_models_ring_density_model_proto_init() {
	if File_pro_models_ring_density_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pro_models_ring_density_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RingDensity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pro_models_ring_density_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Density); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pro_models_ring_density_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RingDensityMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pro_models_ring_density_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pro_models_ring_density_model_proto_goTypes,
		DependencyIndexes: file_pro_models_ring_density_model_proto_depIdxs,
		MessageInfos:      file_pro_models_ring_density_model_proto_msgTypes,
	}.Build()
	File_pro_models_ring_density_model_proto = out.File
	file_pro_models_ring_density_model_proto_rawDesc = nil
	file_pro_models_ring_density_model_proto_goTypes = nil
	file_pro_models_ring_density_model_proto_depIdxs = nil
}
