// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: pro/models/snp_size_model.proto

package snp_size_model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SnpSize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Dn    string  `protobuf:"bytes,2,opt,name=dn,proto3" json:"dn,omitempty"`
	D2    string  `protobuf:"bytes,3,opt,name=d2,proto3" json:"d2,omitempty"`
	Sizes []*Size `protobuf:"bytes,4,rep,name=sizes,proto3" json:"sizes,omitempty"`
}

func (x *SnpSize) Reset() {
	*x = SnpSize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_models_snp_size_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnpSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnpSize) ProtoMessage() {}

func (x *SnpSize) ProtoReflect() protoreflect.Message {
	mi := &file_pro_models_snp_size_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnpSize.ProtoReflect.Descriptor instead.
func (*SnpSize) Descriptor() ([]byte, []int) {
	return file_pro_models_snp_size_model_proto_rawDescGZIP(), []int{0}
}

func (x *SnpSize) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SnpSize) GetDn() string {
	if x != nil {
		return x.Dn
	}
	return ""
}

func (x *SnpSize) GetD2() string {
	if x != nil {
		return x.D2
	}
	return ""
}

func (x *SnpSize) GetSizes() []*Size {
	if x != nil {
		return x.Sizes
	}
	return nil
}

type Size struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pn []*Pn    `protobuf:"bytes,1,rep,name=pn,proto3" json:"pn,omitempty"`
	D4 string   `protobuf:"bytes,2,opt,name=d4,proto3" json:"d4,omitempty"`
	D3 string   `protobuf:"bytes,3,opt,name=d3,proto3" json:"d3,omitempty"`
	D2 string   `protobuf:"bytes,4,opt,name=d2,proto3" json:"d2,omitempty"`
	D1 string   `protobuf:"bytes,5,opt,name=d1,proto3" json:"d1,omitempty"`
	H  []string `protobuf:"bytes,6,rep,name=h,proto3" json:"h,omitempty"`
	S2 []string `protobuf:"bytes,7,rep,name=s2,proto3" json:"s2,omitempty"`
	S3 []string `protobuf:"bytes,8,rep,name=s3,proto3" json:"s3,omitempty"`
}

func (x *Size) Reset() {
	*x = Size{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_models_snp_size_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_pro_models_snp_size_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_pro_models_snp_size_model_proto_rawDescGZIP(), []int{1}
}

func (x *Size) GetPn() []*Pn {
	if x != nil {
		return x.Pn
	}
	return nil
}

func (x *Size) GetD4() string {
	if x != nil {
		return x.D4
	}
	return ""
}

func (x *Size) GetD3() string {
	if x != nil {
		return x.D3
	}
	return ""
}

func (x *Size) GetD2() string {
	if x != nil {
		return x.D2
	}
	return ""
}

func (x *Size) GetD1() string {
	if x != nil {
		return x.D1
	}
	return ""
}

func (x *Size) GetH() []string {
	if x != nil {
		return x.H
	}
	return nil
}

func (x *Size) GetS2() []string {
	if x != nil {
		return x.S2
	}
	return nil
}

func (x *Size) GetS3() []string {
	if x != nil {
		return x.S3
	}
	return nil
}

type Pn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mpa string `protobuf:"bytes,1,opt,name=mpa,proto3" json:"mpa,omitempty"`
	Kg  string `protobuf:"bytes,2,opt,name=kg,proto3" json:"kg,omitempty"`
}

func (x *Pn) Reset() {
	*x = Pn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_models_snp_size_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pn) ProtoMessage() {}

func (x *Pn) ProtoReflect() protoreflect.Message {
	mi := &file_pro_models_snp_size_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pn.ProtoReflect.Descriptor instead.
func (*Pn) Descriptor() ([]byte, []int) {
	return file_pro_models_snp_size_model_proto_rawDescGZIP(), []int{2}
}

func (x *Pn) GetMpa() string {
	if x != nil {
		return x.Mpa
	}
	return ""
}

func (x *Pn) GetKg() string {
	if x != nil {
		return x.Kg
	}
	return ""
}

var File_pro_models_snp_size_model_proto protoreflect.FileDescriptor

var file_pro_models_snp_size_model_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x73, 0x6e, 0x70,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x73, 0x6e, 0x70, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x22, 0x65, 0x0a, 0x07, 0x53, 0x6e, 0x70, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x64, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x64, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x32, 0x12, 0x2a, 0x0a, 0x05,
	0x73, 0x69, 0x7a, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x6e,
	0x70, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x69, 0x7a,
	0x65, 0x52, 0x05, 0x73, 0x69, 0x7a, 0x65, 0x73, 0x22, 0x98, 0x01, 0x0a, 0x04, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x22, 0x0a, 0x02, 0x70, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x73, 0x6e, 0x70, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50,
	0x6e, 0x52, 0x02, 0x70, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x34, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x64, 0x34, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x64, 0x33, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x64, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x64, 0x31, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x64, 0x31, 0x12, 0x0c, 0x0a, 0x01, 0x68, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x01, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x32, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x02, 0x73, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x73, 0x33, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x02, 0x73, 0x33, 0x22, 0x26, 0x0a, 0x02, 0x50, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x70, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x70, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x6b,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6b, 0x67, 0x42, 0x44, 0x5a, 0x42, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6c, 0x65, 0x78, 0x61, 0x6e,
	0x64, 0x65, 0x72, 0x32, 0x37, 0x32, 0x2f, 0x73, 0x65, 0x61, 0x6c, 0x75, 0x72, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2f, 0x73, 0x6e, 0x70, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pro_models_snp_size_model_proto_rawDescOnce sync.Once
	file_pro_models_snp_size_model_proto_rawDescData = file_pro_models_snp_size_model_proto_rawDesc
)

func file_pro_models_snp_size_model_proto_rawDescGZIP() []byte {
	file_pro_models_snp_size_model_proto_rawDescOnce.Do(func() {
		file_pro_models_snp_size_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_pro_models_snp_size_model_proto_rawDescData)
	})
	return file_pro_models_snp_size_model_proto_rawDescData
}

var file_pro_models_snp_size_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pro_models_snp_size_model_proto_goTypes = []interface{}{
	(*SnpSize)(nil), // 0: snp_size_model.SnpSize
	(*Size)(nil),    // 1: snp_size_model.Size
	(*Pn)(nil),      // 2: snp_size_model.Pn
}
var file_pro_models_snp_size_model_proto_depIdxs = []int32{
	1, // 0: snp_size_model.SnpSize.sizes:type_name -> snp_size_model.Size
	2, // 1: snp_size_model.Size.pn:type_name -> snp_size_model.Pn
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pro_models_snp_size_model_proto_init() }
func file_pro_models_snp_size_model_proto_init() {
	if File_pro_models_snp_size_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pro_models_snp_size_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnpSize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pro_models_snp_size_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Size); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pro_models_snp_size_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pro_models_snp_size_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pro_models_snp_size_model_proto_goTypes,
		DependencyIndexes: file_pro_models_snp_size_model_proto_depIdxs,
		MessageInfos:      file_pro_models_snp_size_model_proto_msgTypes,
	}.Build()
	File_pro_models_snp_size_model_proto = out.File
	file_pro_models_snp_size_model_proto_rawDesc = nil
	file_pro_models_snp_size_model_proto_goTypes = nil
	file_pro_models_snp_size_model_proto_depIdxs = nil
}
