// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: pro/putg_filler_api.proto

package putg_filler_api

import (
	putg_filler_model "github.com/Alexander272/sealur_proto/api/pro/models/putg_filler_model"
	response_model "github.com/Alexander272/sealur_proto/api/pro/models/response_model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPutgFiller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConstructionId string `protobuf:"bytes,1,opt,name=constructionId,proto3" json:"constructionId,omitempty"`
}

func (x *GetPutgFiller) Reset() {
	*x = GetPutgFiller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_putg_filler_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPutgFiller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPutgFiller) ProtoMessage() {}

func (x *GetPutgFiller) ProtoReflect() protoreflect.Message {
	mi := &file_pro_putg_filler_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPutgFiller.ProtoReflect.Descriptor instead.
func (*GetPutgFiller) Descriptor() ([]byte, []int) {
	return file_pro_putg_filler_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetPutgFiller) GetConstructionId() string {
	if x != nil {
		return x.ConstructionId
	}
	return ""
}

type GetPutgFiller_New struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StandardId string `protobuf:"bytes,1,opt,name=standardId,proto3" json:"standardId,omitempty"`
}

func (x *GetPutgFiller_New) Reset() {
	*x = GetPutgFiller_New{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_putg_filler_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPutgFiller_New) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPutgFiller_New) ProtoMessage() {}

func (x *GetPutgFiller_New) ProtoReflect() protoreflect.Message {
	mi := &file_pro_putg_filler_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPutgFiller_New.ProtoReflect.Descriptor instead.
func (*GetPutgFiller_New) Descriptor() ([]byte, []int) {
	return file_pro_putg_filler_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetPutgFiller_New) GetStandardId() string {
	if x != nil {
		return x.StandardId
	}
	return ""
}

type CreatePutgFiller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConstructionId string `protobuf:"bytes,1,opt,name=constructionId,proto3" json:"constructionId,omitempty"`
	FillerId       string `protobuf:"bytes,2,opt,name=fillerId,proto3" json:"fillerId,omitempty"`
}

func (x *CreatePutgFiller) Reset() {
	*x = CreatePutgFiller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_putg_filler_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePutgFiller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePutgFiller) ProtoMessage() {}

func (x *CreatePutgFiller) ProtoReflect() protoreflect.Message {
	mi := &file_pro_putg_filler_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePutgFiller.ProtoReflect.Descriptor instead.
func (*CreatePutgFiller) Descriptor() ([]byte, []int) {
	return file_pro_putg_filler_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePutgFiller) GetConstructionId() string {
	if x != nil {
		return x.ConstructionId
	}
	return ""
}

func (x *CreatePutgFiller) GetFillerId() string {
	if x != nil {
		return x.FillerId
	}
	return ""
}

type UpdatePutgFiller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FillerId       string `protobuf:"bytes,2,opt,name=fillerId,proto3" json:"fillerId,omitempty"`
	ConstructionId string `protobuf:"bytes,3,opt,name=constructionId,proto3" json:"constructionId,omitempty"`
}

func (x *UpdatePutgFiller) Reset() {
	*x = UpdatePutgFiller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_putg_filler_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePutgFiller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePutgFiller) ProtoMessage() {}

func (x *UpdatePutgFiller) ProtoReflect() protoreflect.Message {
	mi := &file_pro_putg_filler_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePutgFiller.ProtoReflect.Descriptor instead.
func (*UpdatePutgFiller) Descriptor() ([]byte, []int) {
	return file_pro_putg_filler_api_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePutgFiller) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePutgFiller) GetFillerId() string {
	if x != nil {
		return x.FillerId
	}
	return ""
}

func (x *UpdatePutgFiller) GetConstructionId() string {
	if x != nil {
		return x.ConstructionId
	}
	return ""
}

type DeletePutgFiller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeletePutgFiller) Reset() {
	*x = DeletePutgFiller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_putg_filler_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePutgFiller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePutgFiller) ProtoMessage() {}

func (x *DeletePutgFiller) ProtoReflect() protoreflect.Message {
	mi := &file_pro_putg_filler_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePutgFiller.ProtoReflect.Descriptor instead.
func (*DeletePutgFiller) Descriptor() ([]byte, []int) {
	return file_pro_putg_filler_api_proto_rawDescGZIP(), []int{4}
}

func (x *DeletePutgFiller) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PutgFiller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fillers []*putg_filler_model.PutgFiller `protobuf:"bytes,1,rep,name=fillers,proto3" json:"fillers,omitempty"`
}

func (x *PutgFiller) Reset() {
	*x = PutgFiller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_putg_filler_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PutgFiller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutgFiller) ProtoMessage() {}

func (x *PutgFiller) ProtoReflect() protoreflect.Message {
	mi := &file_pro_putg_filler_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutgFiller.ProtoReflect.Descriptor instead.
func (*PutgFiller) Descriptor() ([]byte, []int) {
	return file_pro_putg_filler_api_proto_rawDescGZIP(), []int{5}
}

func (x *PutgFiller) GetFillers() []*putg_filler_model.PutgFiller {
	if x != nil {
		return x.Fillers
	}
	return nil
}

var File_pro_putg_filler_api_proto protoreflect.FileDescriptor

var file_pro_putg_filler_api_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x2f, 0x70, 0x75, 0x74, 0x67, 0x5f, 0x66, 0x69, 0x6c, 0x6c, 0x65,
	0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x70, 0x75, 0x74,
	0x67, 0x5f, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x70, 0x72,
	0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x70,
	0x72, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x75, 0x74, 0x67, 0x5f, 0x66,
	0x69, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x37, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x75, 0x74, 0x67, 0x46, 0x69, 0x6c, 0x6c,
	0x65, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x11, 0x47, 0x65,
	0x74, 0x50, 0x75, 0x74, 0x67, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x4e, 0x65, 0x77, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22,
	0x56, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75, 0x74, 0x67, 0x46, 0x69, 0x6c,
	0x6c, 0x65, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x22, 0x66, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x75, 0x74, 0x67, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22,
	0x22, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x75, 0x74, 0x67, 0x46, 0x69, 0x6c,
	0x6c, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x0a, 0x50, 0x75, 0x74, 0x67, 0x46, 0x69, 0x6c, 0x6c, 0x65,
	0x72, 0x12, 0x37, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x75, 0x74, 0x67, 0x5f, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x72,
	0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x50, 0x75, 0x74, 0x67, 0x46, 0x69, 0x6c, 0x6c, 0x65,
	0x72, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x73, 0x32, 0xf8, 0x02, 0x0a, 0x11, 0x50,
	0x75, 0x74, 0x67, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x42, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1e, 0x2e, 0x70, 0x75, 0x74, 0x67, 0x5f, 0x66,
	0x69, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75, 0x74,
	0x67, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x1a, 0x1b, 0x2e, 0x70, 0x75, 0x74, 0x67, 0x5f, 0x66,
	0x69, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x75, 0x74, 0x67, 0x46, 0x69,
	0x6c, 0x6c, 0x65, 0x72, 0x12, 0x4a, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x5f, 0x4e, 0x65, 0x77, 0x12,
	0x22, 0x2e, 0x70, 0x75, 0x74, 0x67, 0x5f, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75, 0x74, 0x67, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x5f,
	0x4e, 0x65, 0x77, 0x1a, 0x1b, 0x2e, 0x70, 0x75, 0x74, 0x67, 0x5f, 0x66, 0x69, 0x6c, 0x6c, 0x65,
	0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x75, 0x74, 0x67, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x72,
	0x12, 0x45, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x70, 0x75, 0x74,
	0x67, 0x5f, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x75, 0x74, 0x67, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x1a, 0x18, 0x2e,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x21, 0x2e, 0x70, 0x75, 0x74, 0x67, 0x5f, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x75, 0x74, 0x67, 0x46, 0x69,
	0x6c, 0x6c, 0x65, 0x72, 0x1a, 0x18, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45,
	0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x21, 0x2e, 0x70, 0x75, 0x74, 0x67, 0x5f,
	0x66, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x75, 0x74, 0x67, 0x46, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x1a, 0x18, 0x2e, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x19, 0x5a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f,
	0x2f, 0x70, 0x75, 0x74, 0x67, 0x5f, 0x66, 0x69, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pro_putg_filler_api_proto_rawDescOnce sync.Once
	file_pro_putg_filler_api_proto_rawDescData = file_pro_putg_filler_api_proto_rawDesc
)

func file_pro_putg_filler_api_proto_rawDescGZIP() []byte {
	file_pro_putg_filler_api_proto_rawDescOnce.Do(func() {
		file_pro_putg_filler_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_pro_putg_filler_api_proto_rawDescData)
	})
	return file_pro_putg_filler_api_proto_rawDescData
}

var file_pro_putg_filler_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pro_putg_filler_api_proto_goTypes = []interface{}{
	(*GetPutgFiller)(nil),                // 0: putg_filler_api.GetPutgFiller
	(*GetPutgFiller_New)(nil),            // 1: putg_filler_api.GetPutgFiller_New
	(*CreatePutgFiller)(nil),             // 2: putg_filler_api.CreatePutgFiller
	(*UpdatePutgFiller)(nil),             // 3: putg_filler_api.UpdatePutgFiller
	(*DeletePutgFiller)(nil),             // 4: putg_filler_api.DeletePutgFiller
	(*PutgFiller)(nil),                   // 5: putg_filler_api.PutgFiller
	(*putg_filler_model.PutgFiller)(nil), // 6: putg_filler_model.PutgFiller
	(*response_model.Response)(nil),      // 7: response_model.Response
}
var file_pro_putg_filler_api_proto_depIdxs = []int32{
	6, // 0: putg_filler_api.PutgFiller.fillers:type_name -> putg_filler_model.PutgFiller
	0, // 1: putg_filler_api.PutgFillerService.Get:input_type -> putg_filler_api.GetPutgFiller
	1, // 2: putg_filler_api.PutgFillerService.Get_New:input_type -> putg_filler_api.GetPutgFiller_New
	2, // 3: putg_filler_api.PutgFillerService.Create:input_type -> putg_filler_api.CreatePutgFiller
	3, // 4: putg_filler_api.PutgFillerService.Update:input_type -> putg_filler_api.UpdatePutgFiller
	4, // 5: putg_filler_api.PutgFillerService.Delete:input_type -> putg_filler_api.DeletePutgFiller
	5, // 6: putg_filler_api.PutgFillerService.Get:output_type -> putg_filler_api.PutgFiller
	5, // 7: putg_filler_api.PutgFillerService.Get_New:output_type -> putg_filler_api.PutgFiller
	7, // 8: putg_filler_api.PutgFillerService.Create:output_type -> response_model.Response
	7, // 9: putg_filler_api.PutgFillerService.Update:output_type -> response_model.Response
	7, // 10: putg_filler_api.PutgFillerService.Delete:output_type -> response_model.Response
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pro_putg_filler_api_proto_init() }
func file_pro_putg_filler_api_proto_init() {
	if File_pro_putg_filler_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pro_putg_filler_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPutgFiller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pro_putg_filler_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPutgFiller_New); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pro_putg_filler_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePutgFiller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pro_putg_filler_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePutgFiller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pro_putg_filler_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePutgFiller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pro_putg_filler_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PutgFiller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pro_putg_filler_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pro_putg_filler_api_proto_goTypes,
		DependencyIndexes: file_pro_putg_filler_api_proto_depIdxs,
		MessageInfos:      file_pro_putg_filler_api_proto_msgTypes,
	}.Build()
	File_pro_putg_filler_api_proto = out.File
	file_pro_putg_filler_api_proto_rawDesc = nil
	file_pro_putg_filler_api_proto_goTypes = nil
	file_pro_putg_filler_api_proto_depIdxs = nil
}
