// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: moment/read_api.proto

package read_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReadServiceClient is the client API for ReadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReadServiceClient interface {
	GetFlange(ctx context.Context, in *GetFlangeRequest, opts ...grpc.CallOption) (*GetFlangeResponse, error)
	GetFloat(ctx context.Context, in *GetFloatRequest, opts ...grpc.CallOption) (*GetFloatResponse, error)
	GetDevCooling(ctx context.Context, in *GetDevCoolingtRequest, opts ...grpc.CallOption) (*GetDevCoolingResponse, error)
}

type readServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReadServiceClient(cc grpc.ClientConnInterface) ReadServiceClient {
	return &readServiceClient{cc}
}

func (c *readServiceClient) GetFlange(ctx context.Context, in *GetFlangeRequest, opts ...grpc.CallOption) (*GetFlangeResponse, error) {
	out := new(GetFlangeResponse)
	err := c.cc.Invoke(ctx, "/read_api.ReadService/GetFlange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readServiceClient) GetFloat(ctx context.Context, in *GetFloatRequest, opts ...grpc.CallOption) (*GetFloatResponse, error) {
	out := new(GetFloatResponse)
	err := c.cc.Invoke(ctx, "/read_api.ReadService/GetFloat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *readServiceClient) GetDevCooling(ctx context.Context, in *GetDevCoolingtRequest, opts ...grpc.CallOption) (*GetDevCoolingResponse, error) {
	out := new(GetDevCoolingResponse)
	err := c.cc.Invoke(ctx, "/read_api.ReadService/GetDevCooling", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReadServiceServer is the server API for ReadService service.
// All implementations must embed UnimplementedReadServiceServer
// for forward compatibility
type ReadServiceServer interface {
	GetFlange(context.Context, *GetFlangeRequest) (*GetFlangeResponse, error)
	GetFloat(context.Context, *GetFloatRequest) (*GetFloatResponse, error)
	GetDevCooling(context.Context, *GetDevCoolingtRequest) (*GetDevCoolingResponse, error)
	mustEmbedUnimplementedReadServiceServer()
}

// UnimplementedReadServiceServer must be embedded to have forward compatible implementations.
type UnimplementedReadServiceServer struct {
}

func (UnimplementedReadServiceServer) GetFlange(context.Context, *GetFlangeRequest) (*GetFlangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlange not implemented")
}
func (UnimplementedReadServiceServer) GetFloat(context.Context, *GetFloatRequest) (*GetFloatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFloat not implemented")
}
func (UnimplementedReadServiceServer) GetDevCooling(context.Context, *GetDevCoolingtRequest) (*GetDevCoolingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevCooling not implemented")
}
func (UnimplementedReadServiceServer) mustEmbedUnimplementedReadServiceServer() {}

// UnsafeReadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReadServiceServer will
// result in compilation errors.
type UnsafeReadServiceServer interface {
	mustEmbedUnimplementedReadServiceServer()
}

func RegisterReadServiceServer(s grpc.ServiceRegistrar, srv ReadServiceServer) {
	s.RegisterService(&ReadService_ServiceDesc, srv)
}

func _ReadService_GetFlange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFlangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadServiceServer).GetFlange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/read_api.ReadService/GetFlange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadServiceServer).GetFlange(ctx, req.(*GetFlangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadService_GetFloat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFloatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadServiceServer).GetFloat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/read_api.ReadService/GetFloat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadServiceServer).GetFloat(ctx, req.(*GetFloatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReadService_GetDevCooling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDevCoolingtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadServiceServer).GetDevCooling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/read_api.ReadService/GetDevCooling",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadServiceServer).GetDevCooling(ctx, req.(*GetDevCoolingtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReadService_ServiceDesc is the grpc.ServiceDesc for ReadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "read_api.ReadService",
	HandlerType: (*ReadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFlange",
			Handler:    _ReadService_GetFlange_Handler,
		},
		{
			MethodName: "GetFloat",
			Handler:    _ReadService_GetFloat_Handler,
		},
		{
			MethodName: "GetDevCooling",
			Handler:    _ReadService_GetDevCooling_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moment/read_api.proto",
}
