// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: pro/snp_material_api.proto

package snp_material_api

import (
	response_model "github.com/Alexander272/sealur_proto/api/pro/models/response_model"
	snp_material_model "github.com/Alexander272/sealur_proto/api/pro/models/snp_material_model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSnpMaterial struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StandardId string `protobuf:"bytes,1,opt,name=standardId,proto3" json:"standardId,omitempty"`
}

func (x *GetSnpMaterial) Reset() {
	*x = GetSnpMaterial{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_snp_material_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSnpMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnpMaterial) ProtoMessage() {}

func (x *GetSnpMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_pro_snp_material_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnpMaterial.ProtoReflect.Descriptor instead.
func (*GetSnpMaterial) Descriptor() ([]byte, []int) {
	return file_pro_snp_material_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetSnpMaterial) GetStandardId() string {
	if x != nil {
		return x.StandardId
	}
	return ""
}

type CreateSnpMaterial struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaterialId []string `protobuf:"bytes,1,rep,name=materialId,proto3" json:"materialId,omitempty"`
	Default    string   `protobuf:"bytes,2,opt,name=default,proto3" json:"default,omitempty"`
	Type       string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	StandardId string   `protobuf:"bytes,4,opt,name=standardId,proto3" json:"standardId,omitempty"`
}

func (x *CreateSnpMaterial) Reset() {
	*x = CreateSnpMaterial{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_snp_material_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSnpMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnpMaterial) ProtoMessage() {}

func (x *CreateSnpMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_pro_snp_material_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnpMaterial.ProtoReflect.Descriptor instead.
func (*CreateSnpMaterial) Descriptor() ([]byte, []int) {
	return file_pro_snp_material_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSnpMaterial) GetMaterialId() []string {
	if x != nil {
		return x.MaterialId
	}
	return nil
}

func (x *CreateSnpMaterial) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *CreateSnpMaterial) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateSnpMaterial) GetStandardId() string {
	if x != nil {
		return x.StandardId
	}
	return ""
}

type UpdateSnpMaterial struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MaterialId []string `protobuf:"bytes,2,rep,name=materialId,proto3" json:"materialId,omitempty"`
	Default    string   `protobuf:"bytes,3,opt,name=default,proto3" json:"default,omitempty"`
	Type       string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	StandardId string   `protobuf:"bytes,5,opt,name=standardId,proto3" json:"standardId,omitempty"`
}

func (x *UpdateSnpMaterial) Reset() {
	*x = UpdateSnpMaterial{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_snp_material_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSnpMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSnpMaterial) ProtoMessage() {}

func (x *UpdateSnpMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_pro_snp_material_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSnpMaterial.ProtoReflect.Descriptor instead.
func (*UpdateSnpMaterial) Descriptor() ([]byte, []int) {
	return file_pro_snp_material_api_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateSnpMaterial) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSnpMaterial) GetMaterialId() []string {
	if x != nil {
		return x.MaterialId
	}
	return nil
}

func (x *UpdateSnpMaterial) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *UpdateSnpMaterial) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateSnpMaterial) GetStandardId() string {
	if x != nil {
		return x.StandardId
	}
	return ""
}

type DeleteSnpMaterial struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteSnpMaterial) Reset() {
	*x = DeleteSnpMaterial{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_snp_material_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSnpMaterial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnpMaterial) ProtoMessage() {}

func (x *DeleteSnpMaterial) ProtoReflect() protoreflect.Message {
	mi := &file_pro_snp_material_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnpMaterial.ProtoReflect.Descriptor instead.
func (*DeleteSnpMaterial) Descriptor() ([]byte, []int) {
	return file_pro_snp_material_api_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteSnpMaterial) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SnpMaterials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Materials []*snp_material_model.SnpMaterial `protobuf:"bytes,1,rep,name=materials,proto3" json:"materials,omitempty"`
}

func (x *SnpMaterials) Reset() {
	*x = SnpMaterials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_snp_material_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnpMaterials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnpMaterials) ProtoMessage() {}

func (x *SnpMaterials) ProtoReflect() protoreflect.Message {
	mi := &file_pro_snp_material_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnpMaterials.ProtoReflect.Descriptor instead.
func (*SnpMaterials) Descriptor() ([]byte, []int) {
	return file_pro_snp_material_api_proto_rawDescGZIP(), []int{4}
}

func (x *SnpMaterials) GetMaterials() []*snp_material_model.SnpMaterial {
	if x != nil {
		return x.Materials
	}
	return nil
}

var File_pro_snp_material_api_proto protoreflect.FileDescriptor

var file_pro_snp_material_api_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x2f, 0x73, 0x6e, 0x70, 0x5f, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x73, 0x6e,
	0x70, 0x5f, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x1f,
	0x70, 0x72, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x23, 0x70, 0x72, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x73, 0x6e, 0x70, 0x5f,
	0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x6e, 0x70, 0x4d, 0x61,
	0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61,
	0x72, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x6e,
	0x64, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x6e, 0x70, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x0a,
	0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74,
	0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0x91, 0x01, 0x0a, 0x11, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x70, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x49, 0x64, 0x22, 0x23,
	0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6e, 0x70, 0x4d, 0x61, 0x74, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x4d, 0x0a, 0x0c, 0x53, 0x6e, 0x70, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x73, 0x12, 0x3d, 0x0a, 0x09, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x73, 0x6e, 0x70, 0x5f, 0x6d, 0x61, 0x74,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x6e, 0x70, 0x4d,
	0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x52, 0x09, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x73, 0x32, 0xb8, 0x02, 0x0a, 0x12, 0x53, 0x6e, 0x70, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x03, 0x47, 0x65, 0x74,
	0x12, 0x20, 0x2e, 0x73, 0x6e, 0x70, 0x5f, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6e, 0x70, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x1a, 0x1e, 0x2e, 0x73, 0x6e, 0x70, 0x5f, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x6e, 0x70, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x73, 0x12, 0x47, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x73,
	0x6e, 0x70, 0x5f, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6e, 0x70, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x1a, 0x18, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x23, 0x2e, 0x73, 0x6e, 0x70, 0x5f, 0x6d, 0x61, 0x74, 0x65,
	0x72, 0x69, 0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x6e, 0x70, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x1a, 0x18, 0x2e, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x23,
	0x2e, 0x73, 0x6e, 0x70, 0x5f, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x6e, 0x70, 0x4d, 0x61, 0x74, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x1a, 0x18, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1a, 0x5a,
	0x18, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x2f, 0x73, 0x6e, 0x70, 0x5f, 0x6d, 0x61, 0x74,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pro_snp_material_api_proto_rawDescOnce sync.Once
	file_pro_snp_material_api_proto_rawDescData = file_pro_snp_material_api_proto_rawDesc
)

func file_pro_snp_material_api_proto_rawDescGZIP() []byte {
	file_pro_snp_material_api_proto_rawDescOnce.Do(func() {
		file_pro_snp_material_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_pro_snp_material_api_proto_rawDescData)
	})
	return file_pro_snp_material_api_proto_rawDescData
}

var file_pro_snp_material_api_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pro_snp_material_api_proto_goTypes = []interface{}{
	(*GetSnpMaterial)(nil),                 // 0: snp_material_api.GetSnpMaterial
	(*CreateSnpMaterial)(nil),              // 1: snp_material_api.CreateSnpMaterial
	(*UpdateSnpMaterial)(nil),              // 2: snp_material_api.UpdateSnpMaterial
	(*DeleteSnpMaterial)(nil),              // 3: snp_material_api.DeleteSnpMaterial
	(*SnpMaterials)(nil),                   // 4: snp_material_api.SnpMaterials
	(*snp_material_model.SnpMaterial)(nil), // 5: snp_material_model.SnpMaterial
	(*response_model.Response)(nil),        // 6: response_model.Response
}
var file_pro_snp_material_api_proto_depIdxs = []int32{
	5, // 0: snp_material_api.SnpMaterials.materials:type_name -> snp_material_model.SnpMaterial
	0, // 1: snp_material_api.SnpMaterialService.Get:input_type -> snp_material_api.GetSnpMaterial
	1, // 2: snp_material_api.SnpMaterialService.Create:input_type -> snp_material_api.CreateSnpMaterial
	2, // 3: snp_material_api.SnpMaterialService.Update:input_type -> snp_material_api.UpdateSnpMaterial
	3, // 4: snp_material_api.SnpMaterialService.Delete:input_type -> snp_material_api.DeleteSnpMaterial
	4, // 5: snp_material_api.SnpMaterialService.Get:output_type -> snp_material_api.SnpMaterials
	6, // 6: snp_material_api.SnpMaterialService.Create:output_type -> response_model.Response
	6, // 7: snp_material_api.SnpMaterialService.Update:output_type -> response_model.Response
	6, // 8: snp_material_api.SnpMaterialService.Delete:output_type -> response_model.Response
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pro_snp_material_api_proto_init() }
func file_pro_snp_material_api_proto_init() {
	if File_pro_snp_material_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pro_snp_material_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSnpMaterial); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pro_snp_material_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSnpMaterial); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pro_snp_material_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSnpMaterial); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pro_snp_material_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSnpMaterial); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pro_snp_material_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnpMaterials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pro_snp_material_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pro_snp_material_api_proto_goTypes,
		DependencyIndexes: file_pro_snp_material_api_proto_depIdxs,
		MessageInfos:      file_pro_snp_material_api_proto_msgTypes,
	}.Build()
	File_pro_snp_material_api_proto = out.File
	file_pro_snp_material_api_proto_rawDesc = nil
	file_pro_snp_material_api_proto_goTypes = nil
	file_pro_snp_material_api_proto_depIdxs = nil
}
