// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: pro/rings_kit_api.proto

package rings_kit_api

import (
	rings_kit_model "github.com/Alexander272/sealur_proto/api/pro/models/rings_kit_model"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRingsKit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRingsKit) Reset() {
	*x = GetRingsKit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pro_rings_kit_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRingsKit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRingsKit) ProtoMessage() {}

func (x *GetRingsKit) ProtoReflect() protoreflect.Message {
	mi := &file_pro_rings_kit_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRingsKit.ProtoReflect.Descriptor instead.
func (*GetRingsKit) Descriptor() ([]byte, []int) {
	return file_pro_rings_kit_api_proto_rawDescGZIP(), []int{0}
}

var File_pro_rings_kit_api_proto protoreflect.FileDescriptor

var file_pro_rings_kit_api_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x2f, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x6b, 0x69, 0x74, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x72, 0x69, 0x6e, 0x67, 0x73,
	0x5f, 0x6b, 0x69, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x1a, 0x20, 0x70, 0x72, 0x6f, 0x2f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2f, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x6b, 0x69, 0x74, 0x5f, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x52, 0x69, 0x6e, 0x67, 0x73, 0x4b, 0x69, 0x74, 0x32, 0x4f, 0x0a, 0x0f, 0x52, 0x69, 0x6e,
	0x67, 0x73, 0x4b, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a, 0x03,
	0x47, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x6b, 0x69, 0x74, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x69, 0x6e, 0x67, 0x73, 0x4b, 0x69, 0x74, 0x1a,
	0x19, 0x2e, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x6b, 0x69, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x52, 0x69, 0x6e, 0x67, 0x73, 0x4b, 0x69, 0x74, 0x42, 0x17, 0x5a, 0x15, 0x61, 0x70,
	0x69, 0x2f, 0x70, 0x72, 0x6f, 0x2f, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x6b, 0x69, 0x74, 0x5f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pro_rings_kit_api_proto_rawDescOnce sync.Once
	file_pro_rings_kit_api_proto_rawDescData = file_pro_rings_kit_api_proto_rawDesc
)

func file_pro_rings_kit_api_proto_rawDescGZIP() []byte {
	file_pro_rings_kit_api_proto_rawDescOnce.Do(func() {
		file_pro_rings_kit_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_pro_rings_kit_api_proto_rawDescData)
	})
	return file_pro_rings_kit_api_proto_rawDescData
}

var file_pro_rings_kit_api_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pro_rings_kit_api_proto_goTypes = []interface{}{
	(*GetRingsKit)(nil),              // 0: rings_kit_api.GetRingsKit
	(*rings_kit_model.RingsKit)(nil), // 1: rings_kit_model.RingsKit
}
var file_pro_rings_kit_api_proto_depIdxs = []int32{
	0, // 0: rings_kit_api.RingsKitService.Get:input_type -> rings_kit_api.GetRingsKit
	1, // 1: rings_kit_api.RingsKitService.Get:output_type -> rings_kit_model.RingsKit
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pro_rings_kit_api_proto_init() }
func file_pro_rings_kit_api_proto_init() {
	if File_pro_rings_kit_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pro_rings_kit_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRingsKit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pro_rings_kit_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pro_rings_kit_api_proto_goTypes,
		DependencyIndexes: file_pro_rings_kit_api_proto_depIdxs,
		MessageInfos:      file_pro_rings_kit_api_proto_msgTypes,
	}.Build()
	File_pro_rings_kit_api_proto = out.File
	file_pro_rings_kit_api_proto_rawDesc = nil
	file_pro_rings_kit_api_proto_goTypes = nil
	file_pro_rings_kit_api_proto_depIdxs = nil
}
